import{S,$,el,select,api,on,guarded,url}from'./state.js';
let signature='';
export function init(){const box=$('history-tools');for(const[action,label]of [['select-all','Select all'],['share','Share selected'],['revoke','Revoke sharing'],['final','Mark final'],['export','Export selected'],['delete','Delete selected']]){const b=el('button',label,action==='delete'?'danger':'');b.id='history-'+action;box.append(b);on(b.id,()=>act(action));}S.refreshers.push(render);}
async function act(action){const visible=S.data.images.filter(i=>i.operation!=='mask');if(action==='select-all'){for(const i of visible)if(!i.readonly)S.checked.add(i.id);signature='';return;}
const ids=[...S.checked];if(!ids.length)throw Error('Select image checkboxes first.');if(action==='delete'&&!confirm('Delete selected local files and thumbnails? ComfyUI originals remain in its output folder.'))return;
if(action==='export'){const r=await fetch(`/api/session/${S.sid}/images`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,ids})});if(!r.ok)throw Error((await r.json()).error);const u=URL.createObjectURL(await r.blob()),a=el('a');a.href=u;a.download='images.zip';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}
else await api(`/session/${S.sid}/images`,{action,ids});S.checked.clear();signature='';}
function render(){const images=S.data.images.filter(i=>i.operation!=='mask');const sig=JSON.stringify([S.sid,S.selected,images.map(i=>[i.id,i.shared,i.final]),[...S.checked]]);if(sig!==signature){signature=sig;$('history').replaceChildren();for(const i of images.toReversed()){const card=el('div',undefined,'card'+(S.selected===i.id?' active':''));const img=el('img');img.src=url(i.id,'?thumb=1');img.alt=`Image ${i.id}, ${i.operation}`;img.onclick=()=>select(i.id);card.append(img);const label=el('label');const cb=el('input');cb.type='checkbox';cb.checked=S.checked.has(i.id);cb.onchange=()=>{if(cb.checked)S.checked.add(i.id);else S.checked.delete(i.id);};label.append(cb,el('span',`#${i.id} · ${i.operation}`));card.append(label,el('small',`${i.width} × ${i.height}${i.final?' · Final':''}${i.readonly?' · Read only':i.shared?' · Shared':''}`));$('history').append(card);}}
const mb=n=>(n/1024**2).toFixed(1);$('storage').textContent=`Local ${mb(S.data.storage_bytes)} MB · ComfyUI ${mb(S.data.referenced_bytes)} MB${S.data.storage_bytes>1024**3?' · Over 1 GB target':''}`;}
