import{$,el}from'./state.js';
let strokes=[],current=null;
export function enabled(){return $('mask-enabled')?.checked;}
export function reset(w,h){const c=$('mask-canvas');c.width=w;c.height=h;strokes=[];draw();}
function draw(){const c=$('mask-canvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);for(const s of strokes){ctx.globalCompositeOperation=s.erase?'destination-out':'source-over';ctx.strokeStyle='white';ctx.fillStyle='white';ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=s.size;ctx.beginPath();s.points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));if(s.points.length===1){const[x,y]=s.points[0];ctx.arc(x,y,s.size/2,0,Math.PI*2);ctx.fill();}else ctx.stroke();}ctx.globalCompositeOperation='source-over';}
export function init(){const box=$('mask-tools');box.innerHTML='<label><input type="checkbox" id="mask-enabled"> Paint mask</label><label><input type="checkbox" id="mask-erase"> Erase</label><label>Brush <input id="brush-size" type="range" min="2" max="256" value="60"></label><button id="mask-undo">Undo</button><button id="mask-clear">Clear</button>';
$('mask-enabled').onchange=()=>{$('mask-canvas').style.pointerEvents=enabled()?'auto':'none';};$('mask-undo').onclick=()=>{strokes.pop();draw();};$('mask-clear').onclick=()=>{strokes=[];draw();};
const c=$('mask-canvas');const point=e=>{const r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height];};
c.onpointerdown=e=>{e.stopPropagation();c.setPointerCapture(e.pointerId);current={size:Number($('brush-size').value),erase:$('mask-erase').checked,points:[point(e)]};strokes.push(current);draw();};c.onpointermove=e=>{if(current){current.points.push(point(e));draw();}};c.onpointerup=()=>{current=null;};c.onpointercancel=()=>{current=null;};}
export async function blob(){if(!strokes.length)throw Error('Paint a mask first.');const c=$('mask-canvas'),out=el('canvas');out.width=c.width;out.height=c.height;const ctx=out.getContext('2d');ctx.fillStyle='black';ctx.fillRect(0,0,out.width,out.height);ctx.drawImage(c,0,0);return new Promise(resolve=>out.toBlob(resolve,'image/png'));}
