import {state,on,emit} from './state.js';
import {$,el,button,copy,safe} from './dom.js';
import {api} from './api.js';
import {markdown} from './markdown.js';
import {card,update} from './cards.js';
import {refresh} from './stream.js';
import {earlier} from './paging.js';
export function message(row){const box=el('article',{class:'message '+row.role,'data-message':row.id,'aria-label':row.role==='user'?'You':'Studio'});for(const part of row.parts){if(part.type==='text')box.append(row.role==='user'?el('div',{class:'message-content'},part.text):el('div',{class:'message-content'},markdown(part.text)));else if(part.type==='images')box.append(el('div',{class:'image-grid'},part.images.filter(i=>state.images[i]?.kind!=='mask').map(card)));else if(part.type==='activity')box.append(el('small',{},part.text))}if(row.role==='assistant'){const run=state.runs[row.run_id];if(run?.error)box.append(el('div',{class:'run-error'},el('div',{},run.error),button('Try again',safe(async()=>{await api('/api/runs/'+run.id+'/retry','POST',{});await refresh()})),button('Details',()=>emit('debug',run.id))));if(run?.status==='done'){const images=row.parts.filter(p=>p.type==='images').flatMap(p=>p.images).filter(i=>state.images[i]?.file);const seconds=run.finished&&run.started?Math.round(run.finished-run.started):null;if(images.length)box.append(button('Made '+images.length+' image'+(images.length===1?'':'s')+(seconds?' in '+seconds+' s':'')+' · Details',()=>emit('debug',run.id),{class:'activity-link'}))}if(row.parts.some(p=>p.type==='text'))box.append(el('div',{class:'message-tools'},button('Copy reply',()=>copy(row.parts.filter(p=>p.type==='text').map(p=>p.text).join('\n')))))}return box}
function nearBottom(){const n=$('#thread');return n.scrollHeight-n.scrollTop-n.clientHeight<140}
export function render(){const n=$('#thread'),stick=nearBottom();n.replaceChildren(...state.messages.filter(m=>m.role==='user'||m.role==='assistant').map(message));if(state.before)n.prepend(button('Load previous messages',safe(earlier)));const empty=!state.messages.length;$('#empty').hidden=!empty;n.hidden=empty;if(stick)n.scrollTop=n.scrollHeight;emit('empty',empty)}
on('thread',render);on('message',id=>{const n=$('#thread'),stick=nearBottom();const node=n.querySelector('[data-message="'+id+'"]');const row=state.messages.find(m=>m.id===id);if(node&&row)node.replaceWith(message(row));if(stick)n.scrollTop=n.scrollHeight});on('image',update);
