import {$,el,button,safe} from './dom.js';
import {state,emit,on} from './state.js';
import {api} from './api.js';
import {details,actions,versions} from './viewer_detail.js';
import {mount,controls} from './zoom.js';
import {sync} from './viewer_focus.js';
let requested=0,returnFocus;
export function close(){requested++;$('#viewer').hidden=true;$('#viewer').classList.remove('editing');document.body.classList.remove('viewer-full');state.view=null;sync(close);returnFocus?.focus()}
export async function show(id){const sequence=++requested;const item=await api('/api/images/'+id+'/info');if(sequence!==requested)return;returnFocus=document.activeElement;state.view=item;const box=$('#viewer');box.hidden=false;box.classList.remove('editing');const head=el('header',{},button('←',close,{'aria-label':'Back to chat'}),el('h1',{},'Image · '+item.width+' × '+item.height),button('⤢',()=>{document.body.classList.toggle('viewer-full');sync(close)},{'aria-label':'Expand image viewer'}),button('×',close,{'aria-label':'Close image viewer'}));const downloads=el('div',{class:'viewer-controls'},button('←',()=>next(-1),{'aria-label':'Previous image'}),button('→',()=>next(1),{'aria-label':'Next image'}),el('a',{href:'/api/images/'+id+'?download=1',download:''},'Download PNG'),el('a',{href:'/api/images/'+id+'?format=jpg&download=1',download:''},'JPG'));const body=el('div',{class:'viewer-body'},versions(item),mount(item),controls(),downloads,actions(item));box.replaceChildren(head,body,details(item));if(item.parents?.length)body.append(button('Compare with original',()=>compare(item.parents[0]),{class:'compare-button'}));box.querySelector('button').focus();sync(close)}
function compare(id){const plane=$('.picture-plane');if($('.comparison',plane)){plane.querySelector('.comparison').remove();$('#compare-range')?.remove();return}plane.append(el('img',{class:'comparison',src:'/api/images/'+id,alt:'Original image'}));const input=el('input',{id:'compare-range',class:'compare-range',type:'range',min:0,max:100,value:50,'aria-label':'Before and after comparison',oninput:e=>$('.comparison').style.clipPath=`inset(0 ${100-e.target.value}% 0 0)`});$('.viewer-controls').append(input)}
function next(direction){const ids=Object.values(state.images).filter(i=>i.file&&!i.deleted&&i.kind!=='mask').map(i=>i.id);if(!ids.length)return;const index=ids.indexOf(state.view.id);emit('view',ids[(index+direction+ids.length)%ids.length])}
on('view',safe(show));on('close-view',close);document.addEventListener('keydown',e=>{if(!state.view||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='Escape')close();if(e.key==='ArrowLeft')next(-1);if(e.key==='ArrowRight')next(1)});
